using VoiceBridge;
using System.Collections.Concurrent;

var spoken = new ConcurrentQueue<string>();
var captions = new ConcurrentQueue<string>();
using var pipeline = new TextPipeline(new AppSettings { PhraseDelayMs = 30, PhraseMinChars = 8 });
pipeline.PhraseReady += spoken.Enqueue;
pipeline.CaptionChanged += captions.Enqueue;
void Send(string type, string? text = null) => pipeline.Handle(new BridgeEvent(type, "test", "one", text));
void Check(bool ok, string name) { if (!ok) throw new Exception(name); Console.WriteLine("PASS: " + name); }
Send("start");
Send("text", "Hello ");
Check(captions.Last() == "Hello " && spoken.IsEmpty, "caption appears before phrase timeout");
await Task.Delay(150);
Check(spoken.IsEmpty, "short pauses no longer submit short phrases");
Send("text", "Hello ");
Send("text", "Hello world");
await Task.Delay(150);
Send("complete"); await Task.Delay(800);
Send("complete"); await Task.Delay(800);
Check(string.Concat(spoken) == "Hello world", "snapshot deduplication preserves word spacing");
spoken.Clear();
Send("text", "Hello world stale");
Send("interrupt");
await Task.Delay(150);
Check(spoken.IsEmpty, "interrupt clears pending old phrase");
Send("start");
Send("text", "unfinished");
Send("stop");
await Task.Delay(150);
Check(spoken.IsEmpty, "closing voice does not speak a pending phrase");
Send("start");
var longText = new string('字', 80) + "，还有后半段。";
Send("text", longText);
await Task.Delay(200);
Check(spoken.Count == 1 && spoken.Last() == longText, "complete substantial sentence starts without waiting for whole response");
Send("complete"); await Task.Delay(800);
Check(spoken.Count == 1 && spoken.Last() == longText, "whole completed response submitted once");

spoken.Clear();
Send("interrupt"); Send("start"); Send("text", "保持这段完整回复");
pipeline.Handle(new BridgeEvent("stop", "other-tab", "other"));
Send("complete"); await Task.Delay(800);
Check(spoken.Count == 1 && spoken.Last() == "保持这段完整回复", "inactive source cannot cancel active speech");
spoken.Clear();
Send("interrupt"); Send("start"); Send("text", "这是一句"); Send("complete");
await Task.Delay(100); Send("text", "这是一句完整的话。"); Send("complete");
await Task.Delay(800);
Check(spoken.Count == 1 && spoken.Last() == "这是一句完整的话。", "premature completion merges trailing chunks");

spoken.Clear(); Send("interrupt"); Send("start");
Send("text", "好的，");
Check(spoken.IsEmpty, "tiny comma fragment is retained");
const string firstPhrase = "好的，我现在给你解释一下，";
Send("text", firstPhrase);
Check(spoken.Count == 1 && spoken.Last() == firstPhrase, "comma phrase submitted before sentence completion");
Send("text", firstPhrase);
Send("text", firstPhrase + "后面的内容会接着读。");
Send("complete"); await Task.Delay(300);
Check(string.Concat(spoken) == firstPhrase + "后面的内容会接着读。", "incremental comma phrases are not repeated or lost");
spoken.Clear(); Send("interrupt"); Send("start");
Send("text", "The total is 12,");
Check(spoken.IsEmpty, "numeric comma does not split a number");
Send("interrupt");

spoken.Clear(); Send("start"); Send("text", "这里是旧文字");
Send("text", "这里是修订文字和新追加内容"); Send("complete"); await Task.Delay(300);
Check(spoken.Count == 1 && spoken.Last() == "这里是修订文字和新追加内容", "revised pending snapshot retains new text without old wording");
spoken.Clear(); Send("interrupt"); Send("start");
const string prefix = "先把这一段完整读出来，";
Send("text", prefix + "旧的尾巴");
Send("text", prefix + "新的尾巴和追加内容"); Send("complete"); await Task.Delay(300);
Check(string.Concat(spoken) == prefix + "新的尾巴和追加内容", "revision preserves already submitted prefix without dropping new tail");
