const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context={};vm.runInNewContext(fs.readFileSync(process.argv[2],'utf8'),context);
const tracker=new context.VoiceBridgeTurnTracker();
tracker.baseline('history','Old answer.');
assert.equal(tracker.update('history','Old answer.'),null);
assert.equal(tracker.update('message-1','First phrase.').newTurn,true);
assert.equal(tracker.update('message-1','First phrase. Next phrase.').newTurn,false);
assert.equal(tracker.update('message-1','First phrase. Next phrase.').changed,false);
assert.equal(tracker.update('message-1','Revised phrase.').newTurn,false);
assert.equal(tracker.update('message-2','Next response.').newTurn,true);
tracker.reset();tracker.baseline('message-2','Next response.');
assert.equal(tracker.update('message-2','Next response.'),null);
console.log('PASS: history baseline, same-message remount/update/revision, duplicate snapshot, new reply, restart baseline');
tracker.reset();
const longReply='This is a sufficiently long streamed assistant reply.';
assert.equal(tracker.update('temporary',longReply,'user-1').newTurn,true);
assert.equal(tracker.update('committed',longReply,'user-1').newTurn,false);
assert.equal(tracker.update('committed',longReply,'user-1').changed,false);
assert.equal(tracker.update('another-dom-id',longReply+' More.','user-1').newTurn,false);
assert.equal(tracker.update('new-reply',longReply,'user-2').newTurn,true);
console.log('PASS: committed DOM identity does not replay long answer; tail survives; new user may receive identical answer');
